defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ec75183d-e67e-4265-9967-1156bb06aa09
handle: blog
maxAuthors: 1
minAuthors: 1
name: Blog
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ca499a8e-a51d-4bc8-9ddb-26d3ef6a018f: # cykelbude
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
